default:
    site:
        review_period: '13 months'
        spaces:
            -
                space_path: nxdoc
                space_name: Developer Documentation Center
            -
                space_path: userdoc
                space_name: Nuxeo Platform User Documentation
        dev_browser_path: nxdoc
        version:
            label: FT
development:
    isDev: true
