default:
    site:
        spaces:
            -
                space_path: nxdoc
                space_name: Developer Documentation Center
            -
                space_path: userdoc
                space_name: Nuxeo Platform User Documentation
            -
                space_path: admindoc
                space_name: Nuxeo Installation and Administration
        branch: '60'
        dev_browser_path: nxdoc

development:
    isDev: true
