default:
    site:
        review_period: '6 months'
        review_release_date: 2015-11-09
        review_allow_no_date_set: true
        spaces:
            -
                space_path: nxdoc
                space_name: Developer Documentation Center
            -
                space_path: userdoc
                space_name: Nuxeo Platform User Documentation
            -
                space_path: admindoc
                space_name: Nuxeo Installation and Administration
        branch: '710'
        dev_browser_path: nxdoc

development:
    isDev: true
