default:
    site:
        review_period: '6 months'
        review_release_date: 2016-12-20
        spaces:
            -
                space_path: nxdoc
                space_name: Developer Documentation Center
            -
                space_path: userdoc
                space_name: Nuxeo Platform User Documentation
        branch: '810'
        dev_browser_path: nxdoc
development:
    isDev: true
