default:
    site:
        review_period: '6 months'
        review_release_date: 2016-12-20
        spaces:
            -
                space_path: nxdoc
                space_name: Developer Documentation Center
            -
                space_path: userdoc
                space_name: Nuxeo Platform User Documentation
        branch: '810'
        dev_browser_path: nxdoc
        versions:
            -
                label: FT
            -
                label: LTS 2016
                url_path: '810'
                is_current_version: true
            -
                label: LTS 2015
                url_path: '710'
            -
                label: '6.0'
                url_path: '60'
development:
    isDev: true
