default:
    site:
        review_period: '13 months'
        spaces:
            -
                space_path: nxdoc
                space_name: Developer Documentation Center
            -
                space_path: userdoc
                space_name: Nuxeo Platform User Documentation
        branch: '910'
        dev_browser_path: '910/nxdoc'
        versions:
            -
                label: LTS 2017
                url_path: '910'
                is_current_version: true
development:
    isDev: true
