default:
    site:
        spaces:
            -
                space_path: nxdoc
                space_name: Developer Documentation Center
            -
                space_path: userdoc
                space_name: Nuxeo Platform User Documentation
            -
                space_path: admindoc
                space_name: Nuxeo Installation and Administration
        versions:
            -
                label: FT
            -
                label: LTS 2015
                is_current_version: true
                url_path: '710'
            -
                label: '6.0'
                url_path: '60'

development:
    isDev: true
